trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: env
  value: development

steps:

- script: echo "[$(Build.DefinitionName)]($(env)-$(Build.BuildId)) ($(Build.SourceBranchName)) is being deployed by $(Build.TriggeredBy)"
