trigger:
- main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: DevOps_CI
    type: git
    name: "DevOps HNT/DevOps_CI"

steps:
- checkout: DevOps_CI
- script: ls $(System.DefaultWorkingDirectory)
- script: cat Wpp2Manifests/development/wpp2delivery.yaml