trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- name: IMAGEMM
  value: "CARLOS"
resources:
  repositories:
  - repository: DevOps_CI
    type: git
    name: "DevOps HNT/DevOps_CI"

steps:
- checkout: DevOps_CI
- script: cp Wpp2Manifests/development/wpp2delivery.yaml $(System.DefaultWorkingDirectory)

- ${{ if eq(variables['Build.SourceBranchName'], 'development')  }}:
  - script: cp Wpp2Manifests/development/wpp2delivery.yaml $(System.DefaultWorkingDirectory)
- ${{ elseif eq(variables['Build.SourceBranchName'], 'release/qa_uat') }}:
  - script: cp Wpp2Manifests/homologacao/wpp2delivery.yaml $(System.DefaultWorkingDirectory)

- script: ls $(System.DefaultWorkingDirectory)
- script: cat wpp2delivery.yaml
- script: sed -i "s/{{GENIMAGE}}/$(IMAGEMM)/g" wpp2delivery.yaml
- script: cat wpp2delivery.yaml